const types = {
  SEND_REQUEST_POKEMONS: 'SEND_REQUEST_POKEMONS',
  SEND_REQUEST_POKEMON_SUCCESS: 'SEND_REQUEST_POKEMON_SUCCESS',
  SEND_REQUEST_POKEMON_FAILURE: 'SEND_REQUEST_POKEMON_FAILURE',

  GET_CURRENT_POKEMON: 'GET_CURRENT_POKEMON',
  GET_CURRENT_POKEMON_SUCCESS: 'GET_CURRENT_POKEMON_SUCCESS',
  GET_CURRENT_POKEMON_FAILURE: 'GET_CURRENT_POKEMON_FAILURE'
}
export default types;