const types = {
  SEND_REQUEST_POKEMONS: 'SEND_REQUEST_POKEMONS',
  SEND_REQUEST_POKEMON_SUCCESS: 'SEND_REQUEST_POKEMON_SUCCESS',
  SEND_REQUEST_FAILURE: 'SEND_REQUEST_FAILURE'
}
export default types;