const types = {
  SEND_REQUEST_POKEMONS: 'SEND_REQUEST_POKEMONS',
  SEND_REQUEST_POKEMON_SUCCESS: 'SEND_REQUEST_POKEMON_SUCCESS',
  SEND_REQUEST_FAILURE: 'SEND_REQUEST_FAILURE',
  LOAD_POKEMON_REQUEST: 'LOAD_POKEMON_REQUEST',
  LOAD_POKEMON_REQUEST_SUCCESS: 'LOAD_POKEMON_REQUEST_SUCCESS',
  LOAD_POKEMON_REQUEST_FAILURE: 'LOAD_POKEMON_REQUEST_FAILURE'
}
export default types;